using System;
using System.Collections.Generic;
using System.Text;

namespace Booma.Tools.ItemPMT.JSON
{
    //Autogenerated from: https://json2csharp.com/
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse); 
    public class Range
    {
        public double distH { get; set; }
        public double distV { get; set; }
        public double angleH { get; set; }
        public double angleV { get; set; }
        public int targets { get; set; }
    }

    public class Sfx
    {
        public int aSFX1 { get; set; }
        public int aPitch1 { get; set; }
        public int aSFX2 { get; set; }
        public int aPitch2 { get; set; }
        public int hSFX1 { get; set; }
        public int hPitch1 { get; set; }
        public int hSFX2 { get; set; }
        public int hPitch2 { get; set; }
    }

    public class List
    {
        public string name { get; set; }
        public string desc { get; set; }
        public int stars { get; set; }
        public int announce { get; set; }
        public bool qreward { get; set; }
        public int id { get; set; }
        public int model { get; set; }
        public int texture { get; set; }
        public int teamPoints { get; set; }
        public int _class { get; set; }
        public int atpMin { get; set; }
        public int atpMax { get; set; }
        public int atpReq { get; set; }
        public int mstReq { get; set; }
        public int ataReq { get; set; }
        public int mst { get; set; }
        public int grind { get; set; }
        public int photonColor { get; set; }
        public int special { get; set; }
        public int ata { get; set; }
        public int statBoost { get; set; }
        public int projectile { get; set; }
        public int photonTrail1X { get; set; }
        public int photonTrail1Y { get; set; }
        public int photonTrail2X { get; set; }
        public int photonTrail2Y { get; set; }
        public int photonType { get; set; }
        public int unknown1 { get; set; }
        public int unknown2 { get; set; }
        public int unknown3 { get; set; }
        public int unknown4 { get; set; }
        public int unknown5 { get; set; }
        public int techBoost { get; set; }
        public int attack { get; set; }
    }

    public class Group
    {
        public int animation { get; set; }
        public Range range { get; set; }
        public Sfx sfx { get; set; }
        public double sale { get; set; }
        public List<List> list { get; set; }
    }

    public class Weapons
    {
        public List<Group> group { get; set; }
    }

    public class ItemPMTWeapons
    {
        public Weapons weapons { get; set; }
    }
}
