// <auto-generated />
using System;
using Glader.ASP.GameConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Booma.Server.GameConfigurationService.Migrations
{
    [DbContext(typeof(GameConfigurationDatabaseContext<PsobbGameConfigurationType>))]
    [Migration("20210624070042_AddedPalleteConfig")]
    partial class AddedPalleteConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Glader.ASP.GameConfig.AccountGameConfiguration<Booma.PsobbGameConfigurationType>", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("int");

                    b.HasKey("AccountId", "Type");

                    b.HasIndex("Type");

                    b.ToTable("gameconfig_account");
                });

            modelBuilder.Entity("Glader.ASP.GameConfig.CharacterGameConfiguration<Booma.PsobbGameConfigurationType>", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "Type");

                    b.HasIndex("Type");

                    b.ToTable("gameconfig_character");
                });

            modelBuilder.Entity("Glader.ASP.GameConfig.GameConfigurationType<Booma.PsobbGameConfigurationType>", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VisualName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Type");

                    b.ToTable("gameconfig_type");

                    b.HasData(
                        new
                        {
                            Type = 1,
                            Description = "",
                            VisualName = "Key"
                        },
                        new
                        {
                            Type = 2,
                            Description = "",
                            VisualName = "Joystick"
                        },
                        new
                        {
                            Type = 3,
                            Description = "",
                            VisualName = "ActionBar"
                        });
                });

            modelBuilder.Entity("Glader.ASP.GameConfig.AccountGameConfiguration<Booma.PsobbGameConfigurationType>", b =>
                {
                    b.HasOne("Glader.ASP.GameConfig.GameConfigurationType<Booma.PsobbGameConfigurationType>", "Config")
                        .WithMany()
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Glader.ASP.GameConfig.GameConfigData", "Data", b1 =>
                        {
                            b1.Property<int>("AccountGameConfiguration<PsobbGameConfigurationType>AccountId")
                                .HasColumnType("int");

                            b1.Property<int>("AccountGameConfiguration<PsobbGameConfigurationType>Type")
                                .HasColumnType("int");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnName("data")
                                .HasColumnType("longblob");

                            b1.HasKey("AccountGameConfiguration<PsobbGameConfigurationType>AccountId", "AccountGameConfiguration<PsobbGameConfigurationType>Type");

                            b1.ToTable("gameconfig_account");

                            b1.WithOwner()
                                .HasForeignKey("AccountGameConfiguration<PsobbGameConfigurationType>AccountId", "AccountGameConfiguration<PsobbGameConfigurationType>Type");
                        });
                });

            modelBuilder.Entity("Glader.ASP.GameConfig.CharacterGameConfiguration<Booma.PsobbGameConfigurationType>", b =>
                {
                    b.HasOne("Glader.ASP.GameConfig.GameConfigurationType<Booma.PsobbGameConfigurationType>", "Config")
                        .WithMany()
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Glader.ASP.GameConfig.GameConfigData", "Data", b1 =>
                        {
                            b1.Property<int>("CharacterGameConfiguration<PsobbGameConfigurationType>CharacterId")
                                .HasColumnType("int");

                            b1.Property<int>("CharacterGameConfiguration<PsobbGameConfigurationType>Type")
                                .HasColumnType("int");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnName("data")
                                .HasColumnType("longblob");

                            b1.HasKey("CharacterGameConfiguration<PsobbGameConfigurationType>CharacterId", "CharacterGameConfiguration<PsobbGameConfigurationType>Type");

                            b1.ToTable("gameconfig_character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterGameConfiguration<PsobbGameConfigurationType>CharacterId", "CharacterGameConfiguration<PsobbGameConfigurationType>Type");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
