// <auto-generated />
using System;
using Glader.ASP.GameConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Booma.Server.GameConfigurationService.Migrations
{
    [DbContext(typeof(GameConfigurationDatabaseContext<PsobbGameConfigurationType>))]
    [Migration("20210102094730_InitialGameConfigMigration")]
    partial class InitialGameConfigMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Glader.ASP.GameConfig.AccountKeybindConfiguration", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.ToTable("config_keybinding");
                });

            modelBuilder.Entity("Glader.ASP.GameConfig.AccountKeybindConfiguration", b =>
                {
                    b.OwnsOne("Glader.ASP.GameConfig.KeybindData", "Data", b1 =>
                        {
                            b1.Property<int>("AccountKeybindConfigurationAccountId")
                                .HasColumnType("int");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnName("data")
                                .HasColumnType("longblob");

                            b1.HasKey("AccountKeybindConfigurationAccountId");

                            b1.ToTable("config_keybinding");

                            b1.WithOwner()
                                .HasForeignKey("AccountKeybindConfigurationAccountId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
